apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: contract-compiler-image
build:
  artifacts:
    - image: contract-compiler
      context: ../../../services/event-cannon
      docker:
        dockerfile: Dockerfile.compile-contracts
        buildArgs:
          BASE_AZTEC_IMAGE: "aztecprotocol/aztec:4.2.0"
          NARGO_AZTEC_VERSION: "v4.2.0-aztecnr-rc.2"
          DOCKER_DEFAULT_PLATFORM: "linux/amd64"
  tagPolicy:
    customTemplate:
      template: "4.2.0-aztecnr-rc.2"
