/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TermsAndConditionsLazyImport = createFileRoute('/terms-and-conditions')()
const StakingLazyImport = createFileRoute('/staking')()
const SearchLazyImport = createFileRoute('/search')()
const PrivacyPolicyLazyImport = createFileRoute('/privacy-policy')()
const FeeRecipientsLazyImport = createFileRoute('/fee-recipients')()
const EcosystemLazyImport = createFileRoute('/ecosystem')()
const AboutUsLazyImport = createFileRoute('/about-us')()
const IndexLazyImport = createFileRoute('/')()
const ValidatorsIndexLazyImport = createFileRoute('/validators/')()
const TxEffectsIndexLazyImport = createFileRoute('/tx-effects/')()
const HealthIndexLazyImport = createFileRoute('/health/')()
const ContractsIndexLazyImport = createFileRoute('/contracts/')()
const BlocksIndexLazyImport = createFileRoute('/blocks/')()
const ValidatorsAttesterAddressLazyImport = createFileRoute(
  '/validators/$attesterAddress',
)()
const TxEffectsHashLazyImport = createFileRoute('/tx-effects/$hash')()
const L1ContractEventsLazyImport = createFileRoute('/l1/contract-events')()
const HealthAztecscanLazyImport = createFileRoute('/health/aztecscan')()
const BlocksBlockNumberLazyImport = createFileRoute('/blocks/$blockNumber')()
const AddressAddressLazyImport = createFileRoute('/address/$address')()
const L1AddressAddressLazyImport = createFileRoute('/l1/address/$address')()
const ContractsInstancesAddressLazyImport = createFileRoute(
  '/contracts/instances/$address',
)()
const ContractsClassesIdVersionsVersionLazyImport = createFileRoute(
  '/contracts/classes/$id/versions/$version',
)()
const ContractsClassesIdVersionsVersionSubmitStandardContractLazyImport =
  createFileRoute(
    '/contracts/classes/$id/versions/$version/submit-standard-contract',
  )()

// Create/Update Routes

const TermsAndConditionsLazyRoute = TermsAndConditionsLazyImport.update({
  path: '/terms-and-conditions',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/terms-and-conditions.lazy').then((d) => d.Route),
)

const StakingLazyRoute = StakingLazyImport.update({
  path: '/staking',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/staking.lazy').then((d) => d.Route))

const SearchLazyRoute = SearchLazyImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))

const PrivacyPolicyLazyRoute = PrivacyPolicyLazyImport.update({
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)

const FeeRecipientsLazyRoute = FeeRecipientsLazyImport.update({
  path: '/fee-recipients',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/fee-recipients.lazy').then((d) => d.Route),
)

const EcosystemLazyRoute = EcosystemLazyImport.update({
  path: '/ecosystem',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ecosystem.lazy').then((d) => d.Route))

const AboutUsLazyRoute = AboutUsLazyImport.update({
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about-us.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ValidatorsIndexLazyRoute = ValidatorsIndexLazyImport.update({
  path: '/validators/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/validators/index.lazy').then((d) => d.Route),
)

const TxEffectsIndexLazyRoute = TxEffectsIndexLazyImport.update({
  path: '/tx-effects/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tx-effects/index.lazy').then((d) => d.Route),
)

const HealthIndexLazyRoute = HealthIndexLazyImport.update({
  path: '/health/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/health/index.lazy').then((d) => d.Route))

const ContractsIndexLazyRoute = ContractsIndexLazyImport.update({
  path: '/contracts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contracts/index.lazy').then((d) => d.Route),
)

const BlocksIndexLazyRoute = BlocksIndexLazyImport.update({
  path: '/blocks/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/blocks/index.lazy').then((d) => d.Route))

const ValidatorsAttesterAddressLazyRoute =
  ValidatorsAttesterAddressLazyImport.update({
    path: '/validators/$attesterAddress',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/validators/$attesterAddress.lazy').then((d) => d.Route),
  )

const TxEffectsHashLazyRoute = TxEffectsHashLazyImport.update({
  path: '/tx-effects/$hash',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tx-effects/$hash.lazy').then((d) => d.Route),
)

const L1ContractEventsLazyRoute = L1ContractEventsLazyImport.update({
  path: '/l1/contract-events',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/l1/contract-events.lazy').then((d) => d.Route),
)

const HealthAztecscanLazyRoute = HealthAztecscanLazyImport.update({
  path: '/health/aztecscan',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/health/aztecscan.lazy').then((d) => d.Route),
)

const BlocksBlockNumberLazyRoute = BlocksBlockNumberLazyImport.update({
  path: '/blocks/$blockNumber',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/blocks/$blockNumber.lazy').then((d) => d.Route),
)

const AddressAddressLazyRoute = AddressAddressLazyImport.update({
  path: '/address/$address',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/address.$address.lazy').then((d) => d.Route),
)

const L1AddressAddressLazyRoute = L1AddressAddressLazyImport.update({
  path: '/l1/address/$address',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/l1/address.$address.lazy').then((d) => d.Route),
)

const ContractsInstancesAddressLazyRoute =
  ContractsInstancesAddressLazyImport.update({
    path: '/contracts/instances/$address',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/contracts/instances.$address.lazy').then((d) => d.Route),
  )

const ContractsClassesIdVersionsVersionLazyRoute =
  ContractsClassesIdVersionsVersionLazyImport.update({
    path: '/contracts/classes/$id/versions/$version',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/contracts/classes.$id.versions.$version.lazy').then(
      (d) => d.Route,
    ),
  )

const ContractsClassesIdVersionsVersionSubmitStandardContractLazyRoute =
  ContractsClassesIdVersionsVersionSubmitStandardContractLazyImport.update({
    path: '/submit-standard-contract',
    getParentRoute: () => ContractsClassesIdVersionsVersionLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/contracts/classes.$id.versions.$version.submit-standard-contract.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsLazyImport
      parentRoute: typeof rootRoute
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemLazyImport
      parentRoute: typeof rootRoute
    }
    '/fee-recipients': {
      id: '/fee-recipients'
      path: '/fee-recipients'
      fullPath: '/fee-recipients'
      preLoaderRoute: typeof FeeRecipientsLazyImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingLazyImport
      parentRoute: typeof rootRoute
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsLazyImport
      parentRoute: typeof rootRoute
    }
    '/address/$address': {
      id: '/address/$address'
      path: '/address/$address'
      fullPath: '/address/$address'
      preLoaderRoute: typeof AddressAddressLazyImport
      parentRoute: typeof rootRoute
    }
    '/blocks/$blockNumber': {
      id: '/blocks/$blockNumber'
      path: '/blocks/$blockNumber'
      fullPath: '/blocks/$blockNumber'
      preLoaderRoute: typeof BlocksBlockNumberLazyImport
      parentRoute: typeof rootRoute
    }
    '/health/aztecscan': {
      id: '/health/aztecscan'
      path: '/health/aztecscan'
      fullPath: '/health/aztecscan'
      preLoaderRoute: typeof HealthAztecscanLazyImport
      parentRoute: typeof rootRoute
    }
    '/l1/contract-events': {
      id: '/l1/contract-events'
      path: '/l1/contract-events'
      fullPath: '/l1/contract-events'
      preLoaderRoute: typeof L1ContractEventsLazyImport
      parentRoute: typeof rootRoute
    }
    '/tx-effects/$hash': {
      id: '/tx-effects/$hash'
      path: '/tx-effects/$hash'
      fullPath: '/tx-effects/$hash'
      preLoaderRoute: typeof TxEffectsHashLazyImport
      parentRoute: typeof rootRoute
    }
    '/validators/$attesterAddress': {
      id: '/validators/$attesterAddress'
      path: '/validators/$attesterAddress'
      fullPath: '/validators/$attesterAddress'
      preLoaderRoute: typeof ValidatorsAttesterAddressLazyImport
      parentRoute: typeof rootRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/tx-effects/': {
      id: '/tx-effects/'
      path: '/tx-effects'
      fullPath: '/tx-effects'
      preLoaderRoute: typeof TxEffectsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/validators/': {
      id: '/validators/'
      path: '/validators'
      fullPath: '/validators'
      preLoaderRoute: typeof ValidatorsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contracts/instances/$address': {
      id: '/contracts/instances/$address'
      path: '/contracts/instances/$address'
      fullPath: '/contracts/instances/$address'
      preLoaderRoute: typeof ContractsInstancesAddressLazyImport
      parentRoute: typeof rootRoute
    }
    '/l1/address/$address': {
      id: '/l1/address/$address'
      path: '/l1/address/$address'
      fullPath: '/l1/address/$address'
      preLoaderRoute: typeof L1AddressAddressLazyImport
      parentRoute: typeof rootRoute
    }
    '/contracts/classes/$id/versions/$version': {
      id: '/contracts/classes/$id/versions/$version'
      path: '/contracts/classes/$id/versions/$version'
      fullPath: '/contracts/classes/$id/versions/$version'
      preLoaderRoute: typeof ContractsClassesIdVersionsVersionLazyImport
      parentRoute: typeof rootRoute
    }
    '/contracts/classes/$id/versions/$version/submit-standard-contract': {
      id: '/contracts/classes/$id/versions/$version/submit-standard-contract'
      path: '/submit-standard-contract'
      fullPath: '/contracts/classes/$id/versions/$version/submit-standard-contract'
      preLoaderRoute: typeof ContractsClassesIdVersionsVersionSubmitStandardContractLazyImport
      parentRoute: typeof ContractsClassesIdVersionsVersionLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutUsLazyRoute,
  EcosystemLazyRoute,
  FeeRecipientsLazyRoute,
  PrivacyPolicyLazyRoute,
  SearchLazyRoute,
  StakingLazyRoute,
  TermsAndConditionsLazyRoute,
  AddressAddressLazyRoute,
  BlocksBlockNumberLazyRoute,
  HealthAztecscanLazyRoute,
  L1ContractEventsLazyRoute,
  TxEffectsHashLazyRoute,
  ValidatorsAttesterAddressLazyRoute,
  BlocksIndexLazyRoute,
  ContractsIndexLazyRoute,
  HealthIndexLazyRoute,
  TxEffectsIndexLazyRoute,
  ValidatorsIndexLazyRoute,
  ContractsInstancesAddressLazyRoute,
  L1AddressAddressLazyRoute,
  ContractsClassesIdVersionsVersionLazyRoute:
    ContractsClassesIdVersionsVersionLazyRoute.addChildren({
      ContractsClassesIdVersionsVersionSubmitStandardContractLazyRoute,
    }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about-us",
        "/ecosystem",
        "/fee-recipients",
        "/privacy-policy",
        "/search",
        "/staking",
        "/terms-and-conditions",
        "/address/$address",
        "/blocks/$blockNumber",
        "/health/aztecscan",
        "/l1/contract-events",
        "/tx-effects/$hash",
        "/validators/$attesterAddress",
        "/blocks/",
        "/contracts/",
        "/health/",
        "/tx-effects/",
        "/validators/",
        "/contracts/instances/$address",
        "/l1/address/$address",
        "/contracts/classes/$id/versions/$version"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about-us": {
      "filePath": "about-us.lazy.tsx"
    },
    "/ecosystem": {
      "filePath": "ecosystem.lazy.tsx"
    },
    "/fee-recipients": {
      "filePath": "fee-recipients.lazy.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.lazy.tsx"
    },
    "/search": {
      "filePath": "search.lazy.tsx"
    },
    "/staking": {
      "filePath": "staking.lazy.tsx"
    },
    "/terms-and-conditions": {
      "filePath": "terms-and-conditions.lazy.tsx"
    },
    "/address/$address": {
      "filePath": "address.$address.lazy.tsx"
    },
    "/blocks/$blockNumber": {
      "filePath": "blocks/$blockNumber.lazy.tsx"
    },
    "/health/aztecscan": {
      "filePath": "health/aztecscan.lazy.tsx"
    },
    "/l1/contract-events": {
      "filePath": "l1/contract-events.lazy.tsx"
    },
    "/tx-effects/$hash": {
      "filePath": "tx-effects/$hash.lazy.tsx"
    },
    "/validators/$attesterAddress": {
      "filePath": "validators/$attesterAddress.lazy.tsx"
    },
    "/blocks/": {
      "filePath": "blocks/index.lazy.tsx"
    },
    "/contracts/": {
      "filePath": "contracts/index.lazy.tsx"
    },
    "/health/": {
      "filePath": "health/index.lazy.tsx"
    },
    "/tx-effects/": {
      "filePath": "tx-effects/index.lazy.tsx"
    },
    "/validators/": {
      "filePath": "validators/index.lazy.tsx"
    },
    "/contracts/instances/$address": {
      "filePath": "contracts/instances.$address.lazy.tsx"
    },
    "/l1/address/$address": {
      "filePath": "l1/address.$address.lazy.tsx"
    },
    "/contracts/classes/$id/versions/$version": {
      "filePath": "contracts/classes.$id.versions.$version.lazy.tsx",
      "children": [
        "/contracts/classes/$id/versions/$version/submit-standard-contract"
      ]
    },
    "/contracts/classes/$id/versions/$version/submit-standard-contract": {
      "filePath": "contracts/classes.$id.versions.$version.submit-standard-contract.lazy.tsx",
      "parent": "/contracts/classes/$id/versions/$version"
    }
  }
}
ROUTE_MANIFEST_END */
