
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import ExplorerShowcaseContractArtifactJson from '../contract-projects/ExplorerShowcase/target/explorer_showcase-ExplorerShowcase.json' with { type: 'json' };
export const ExplorerShowcaseContractArtifact = loadContractArtifact(ExplorerShowcaseContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ExplorerShowcase;
 */
export class ExplorerShowcaseContract extends ContractBase {

  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, ExplorerShowcaseContractArtifact, wallet);
  }



  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): ExplorerShowcaseContract {
    return Contract.at(address, ExplorerShowcaseContract.artifact, wallet) as ExplorerShowcaseContract;
  }


  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<ExplorerShowcaseContract>(
      wallet,
      {
        artifact: ExplorerShowcaseContractArtifact,
        postDeployCtor: (instance, wallet) => ExplorerShowcaseContract.at(instance.address, wallet),
        args: [admin],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ExplorerShowcaseContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<ExplorerShowcaseContract['methods'][M]>
  ) {
    return DeployMethod.create<ExplorerShowcaseContract>(
      opts.wallet,
      {
        artifact: ExplorerShowcaseContractArtifact,
        postDeployCtor: (instance, wallet) => ExplorerShowcaseContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }



  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ExplorerShowcaseContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(ExplorerShowcaseContractArtifactJson as NoirCompiledContract);
  }


  public static get storage(): ContractStorageLayout<'admin' | 'public_counters' | 'private_balances'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
public_counters: {
      slot: new Fr(3n),
    },
private_balances: {
      slot: new Fr(4n),
    }
      } as ContractStorageLayout<'admin' | 'public_counters' | 'private_balances'>;
    }


  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {

    /** add_private_balance(amount: integer) */
    add_private_balance: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_l1_message(content: field, secret: field, sender: struct, leaf_index: field) */
    claim_l1_message: ((content: FieldLike, secret: FieldLike, sender: EthAddressLike, leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** emit_message(tag: field, content: field) */
    emit_message: ((tag: FieldLike, content: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_public_counter(owner: struct) */
    get_public_counter: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** increment_public(owner: struct) */
    increment_public: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize(admin: struct) */
    initialize: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** shield(amount: integer) */
    shield: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private(to: struct, amount: integer) */
    transfer_private: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unshield(amount: integer) */
    unshield: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };


}
