apiVersion: v1
kind: Service
metadata:
  name: explorer-api
  labels:
    app.kubernetes.io/name: explorer-api
    app.kubernetes.io/part-of: chicmoz-prod
spec:
  selector:
    app: explorer-api
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: http-app-port
