apiVersion: v1
kind: Service
metadata:
  name: dummy-node
  namespace: chicmoz
spec:
  selector:
    app: dummy-node
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: http-app
