apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-explorer-ui
  namespace: chicmoz-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "chicmoz-issuer-production"
spec:
  ingressClassName: nginx
  tls:
    - secretName: chicmoz-issuer-platform
      hosts:
        - chicmoz.info
  rules:
    - host: chicmoz.info # TODO: change to env-var "DOMAIN"
      http:
        paths:
          - backend:
              service:
                name: explorer-ui
                port:
                  name: http-app
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
