apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-explorer-ui
  namespace: chicmoz-prod
  annotations:
    cert-manager.io/cluster-issuer: "aztecscout-issuer-production"
spec:
  ingressClassName: nginx
  tls:
    - secretName: aztecscout-ui-tls
      hosts:
        - aztecscout.xyz
        - aztecscan.io
  rules:
    - host: aztecscout.xyz # TODO: change to env-var "DOMAIN"
      http:
        paths:
          - backend:
              service:
                name: explorer-ui
                port:
                  name: http-app
            path: /
            pathType: Prefix
    - host: aztecscan.io
      http:
        paths:
          - backend:
              service:
                name: explorer-ui
                port:
                  name: http-app
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
