apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-swagger
  namespace: chicmoz
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: swagger.chicmoz.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swagger-service
                port:
                  name: http
status:
  loadBalancer: {}
