apiVersion: v1
kind: Service
metadata:
  name: swagger-service-external
  namespace: chicmoz-staging
spec:
  type: NodePort
  selector:
    app: swagger # Match your swagger pod labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: http # or whatever port your swagger service uses
      nodePort: 30083
