apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorer-api
  name: explorer-api
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-api
  strategy: {}
  template:
    metadata:
      labels:
        app: explorer-api
    spec:
      imagePullSecrets:
        - name: registry-aztlan-containers
      initContainers:
        - image: registry.digitalocean.com/aztlan-containers/explorer-api:latest
          name: run-migrations
          command: ["yarn", run, "migrate"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "explorer_api"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
      containers:
        - image: registry.digitalocean.com/aztlan-containers/explorer-api:latest
          name: explorer-api
          resources:
            limits:
              memory: 4096Mi
              cpu: 350m
          ports:
            - name: http-app
              containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "80"
            - name: NETWORK_NAME
              value: "SANDBOX"
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "explorer_api"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password" # TODO: change to env-var
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
status: {}
