export { run as deployAndInteractFunctionsVote } from "./deploy-and-interact-vote-contract.js";
export { run as deploySimpleContract } from "./simple-deploy-contract.js";
export { run as deploySimpleDefaultAccount } from "./deploy-simple-default-account.js";
export { run as deployAndInteractTokenContract } from "./deploy-and-interact-token-contract.js";
export { run as deploySimpleLog } from "./deploy-and-run-simple-log.js";
export { run as l1L2PublicMessaging } from "./l1-l2-public-messaging.js";
export { run as l1L2PrivateMessaging } from "./l1-l2-private-messaging.js";
// export { run as deployAndUpdateSimpleContract } from "./deploy-and-update-simple-contract.ts.old";
export { run as deployAztecStandardTokenContractCurrent } from "./deploy-aztec-standard-token-contract-current.js";
export { run as deployAztecStandardTokenContractLegacy } from "./deploy-aztec-standard-token-contract-legacy.js";
export { run as verifySourceCode } from "./verify-source-code.js";
export { run as deployAndInteractWithFpc } from "./deploy-and-interact-with-fpc.js";
