apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: explorer-ui
    app.kubernetes.io/part-of: chicmoz-prod
  name: explorer-ui-testnet
  namespace: chicmoz-prod
spec:
  ports:
    - name: http-app
      port: 80
      protocol: TCP
      targetPort: http-app-port
  selector:
    app: explorer-ui
    network: testnet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorer-ui
    app.kubernetes.io/name: explorer-ui
    app.kubernetes.io/part-of: chicmoz-prod
  name: explorer-ui-testnet
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-ui
      network: testnet
  template:
    metadata:
      labels:
        app: explorer-ui
        network: testnet
    spec:
      containers:
        - image: registry.digitalocean.com/aztlan-containers/explorer-ui-testnet:latest
          imagePullPolicy: Always
          name: explorer-ui
          ports:
            - containerPort: 80
              name: http-app-port
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
      imagePullSecrets:
        - name: registry-aztlan-containers
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/name: explorer-ui
    app.kubernetes.io/part-of: chicmoz-prod
  name: explorer-ui-testnet
  namespace: chicmoz-prod
spec:
  hostnames:
    - testnet.aztecscan.xyz
  parentRefs:
    - name: aztecscan-gateway
      sectionName: ui-testnet-primary-http
    - name: aztecscan-gateway
      sectionName: ui-testnet-primary-https
  rules:
    - backendRefs:
        - name: explorer-ui-testnet
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
