apiVersion: v1
kind: Service
metadata:
  name: auth-service-external
  namespace: chicmoz-staging
spec:
  type: NodePort
  selector:
    app: auth-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
