apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-label
  name: auth-deployment
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-label
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-label
    spec:
      containers:
        - image: auth:latest
          resources:
            limits:
              memory: 500Mi
              cpu: 50m
          ports:
            - name: http-app-port
              containerPort: 80
              protocol: TCP
          name: auth
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-auth
          env:
            - name: PORT
              value: "80"
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: NODE_ENV
              value: "development"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
status: {}
