apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: chicmoz
spec:
  selector:
    app: auth-label
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: http-app-port
