apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ./common/skaffold.base.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ./remote_devnet/postgres-config.yaml
    - ./remote_devnet/service.yaml
    - ./remote_devnet/deployment.yaml
