apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chicmoz-prod
nameSuffix: -devnet

resources:
  - ../../base
  - httproute.yaml
  - postgres-config.yaml
  - http-filter.yaml
  - securitypolicy.yaml

images:
  - name: registry.digitalocean.com/aztlan-containers/explorer-api
    newName: registry.digitalocean.com/aztlan-containers/explorer-api-devnet
    newTag: latest

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: explorer-api
      spec:
        template:
          spec:
            containers:
              - name: explorer-api
                env:
                  - name: INSTANCE_NAME
                    value: "devnet_explorer-api"
                  - name: L2_NETWORK_ID
                    value: "DEVNET"
                  - name: REDIS_HOST
                    value: "redis-cache"
            initContainers:
              - name: run-migrations
                env:
                  - name: INSTANCE_NAME
                    value: "devnet_explorer-api"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: explorer-api
      spec:
        selector:
          matchLabels:
            app: explorer-api
            network: devnet
        template:
          metadata:
            labels:
              app: explorer-api
              network: devnet
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: explorer-api
      spec:
        selector:
          app: explorer-api
          network: devnet
