apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: chicmoz
requires:
  - path: ./chicmoz-base-image.yaml
  #- path: ./explorer-ui/image.yaml
  - path: ./explorer-api/image.yaml
  #- path: ./websocket-event-publisher/image.yaml
  #- path: ./auth/image.yaml
  #- path: ./aztec-listener/image.yaml
  #- path: ./ethereum-listener/image.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - k8s/local/common/namespace.yaml
    #- k8s/local/explorer-ui/ingress.yaml
    #- k8s/local/explorer-ui/deployment.yaml
    #- k8s/local/explorer-ui/service.yaml
    - k8s/local/explorer-api/ingress.yaml
    - k8s/local/explorer-api/deployment.yaml
    - k8s/local/explorer-api/service.yaml
    - k8s/local/explorer-api/postgres-config.yaml
    #- k8s/local/websocket-event-publisher/ingress.yaml
    #- k8s/local/websocket-event-publisher/deployment.yaml
    #- k8s/local/websocket-event-publisher/service.yaml
    #- k8s/local/auth/deployment.yaml
    #- k8s/local/auth/service.yaml
    #- k8s/local/aztec-listener/remote_sp_testnet_deployment.yaml
    #- k8s/local/ethereum-listener/remote_sp_testnet_deployment.yaml
    - k8s/local/postgres-config.yaml
  #helm:
  #  releases:
  #    - name: ingress-nginx
  #      remoteChart: ingress-nginx
  #      repo: https://kubernetes.github.io/ingress-nginx
  #      namespace: chicmoz
  #      createNamespace: false
  #      recreatePods: false
  #      skipBuildDependencies: false
  #      useHelmSecrets: false
  #      wait: false
  #    - name: postgresql
  #      version: 12.10.0
  #      remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
  #      valuesFiles:
  #        - k8s/local/postgres/values.yaml
  #      setValues:
  #        global.postgresql.auth.postgresPassword: "secret-local-password"
  #        global.postgresql.auth.username: "admin"
  #        global.postgresql.auth.password: "secret-local-password"
  #        image.debug: true
  #      namespace: chicmoz
  #      createNamespace: false
  #      recreatePods: false
  #      skipBuildDependencies: false
  #      useHelmSecrets: false
  #      wait: false
  #    - name: redis
  #      version: 18.17.1
  #      remoteChart: oci://registry-1.docker.io/bitnamicharts/redis
  #      namespace: chicmoz
  #      createNamespace: false
  #      recreatePods: false
  #      skipBuildDependencies: false
  #      useHelmSecrets: false
  #      wait: false
  #      setValues:
  #        auth.enabled: false
  #        master.configuration: |
  #          maxmemory 100mb
  #          maxmemory-policy volatile-ttl
  #          lazyfree-lazy-eviction yes
  #        replica.configuration: |
  #          maxmemory 100mb
  #          maxmemory-policy volatile-ttl
  #          lazyfree-lazy-eviction yes
  #        persistence.enabled: false
  #    - name: kafka
  #      version: 26.4.2
  #      remoteChart: oci://registry-1.docker.io/bitnamicharts/kafka
  #      namespace: chicmoz
  #      setValues:
  #        sasl.enabledMechanisms: plain
  #        sasl.controllerMechanism: plain
  #        sasl.interBrokerMechanism: plain
  #        sasl.controller.user: controller_user
  #        sasl.controller.password: test
  #        sasl.interbroker.user: inter_broker_user
  #        sasl.interbroker.password: test
  #        sasl.client.users:
  #          - controller_user
  #        sasl.client.passwords:
  #          - test
  #        extraConfig: |
  #          message.max.bytes=10000000
  #      createNamespace: false
  #      recreatePods: true
  #      skipBuildDependencies: false
  #      useHelmSecrets: false
  #      wait: false
