apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: chicmoz
requires:
  - path: ./chicmoz-base-image.yaml
  - path: ./event-cannon/image.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - k8s/local/event-cannon/deployment.yaml
