apiVersion: skaffold/v4beta6
kind: Config
requires:
  - configs: ["chicmoz-dev-base-image"]
    path: ./chicmoz-base-image.yaml
  - configs: ["chicmoz-dev-explorer-api-image"]
    path: ./explorer-api/image.yaml
  - configs: ["chicmoz-dev-websocket-event-publisher-image"]
    path: ./websocket-event-publisher/image.yaml
  - configs: ["chicmoz-dev-auth-image"]
    path: ./auth/image.yaml
  - configs: ["chicmoz-dev-aztec-event-cannon-image"]
    path: ./aztec-event-cannon/image.yaml
  - configs: ["chicmoz-dev-aztec-listener-image"]
    path: ./aztec-listener/image.yaml
metadata:
  name: chicmoz
build:
manifests:
  rawYaml:
    - ./explorer-api/ingress.yaml
    - ./explorer-api/deployment.yaml
    - ./explorer-api/service.yaml
    - ./websocket-event-publisher/ingress.yaml
    - ./websocket-event-publisher/deployment.yaml
    - ./websocket-event-publisher/service.yaml
    - ./auth/deployment.yaml
    - ./auth/service.yaml
    - ./aztec-event-cannon/deployment.yaml
    - ./aztec-listener/deployment.yaml
