apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: no_ui
requires:
  - path: ./common/skaffold.manifests.yaml
  - path: ./common/skaffold.aztec_sanbox_nodes.yaml
  - path: ./auth/image.yaml
  - path: ./event-cannon/image.yaml
  - path: ./aztec-listener/skaffold.sandbox.yaml
  - path: ./ethereum-listener/skaffold.sandbox.yaml
  - path: ./explorer-api/skaffold.sandbox.yaml
  - path: ./websocket-event-publisher/skaffold.sandbox.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ./auth/deployment.yaml
    - ./auth/service.yaml
    - ./auth/postgres-config.yaml
    - ./event-cannon/deployment.yaml
