apiVersion: skaffold/v4beta6
kind: Config
requires:
  - configs: ["chicmoz-dev-base-image"]
    path: ./chicmoz-base-image.yaml
  - configs: ["chicmoz-dev-explorer-ui-image"]
    path: ./chicmoz-explorer-ui-image.yaml
  - configs: ["chicmoz-dev-explorer-api-image"]
    path: ./chicmoz-explorer-api-image.yaml
  - configs: ["chicmoz-dev-websocket-event-publisher-image"]
    path: ./chicmoz-websocket-event-publisher-image.yaml
  - configs: ["chicmoz-dev-auth-image"]
    path: ./chicmoz-auth-image.yaml
  - configs: ["chicmoz-dev-aztec-event-cannon-image"]
    path: ./chicmoz-aztec-event-cannon-image.yaml
  - configs: ["chicmoz-dev-ethereum-listener-image"]
    path: ./chicmoz-ethereum-listener-image.yaml
  - configs: ["chicmoz-dev-aztec-listener-image"]
    path: ./chicmoz-aztec-listener-image.yaml
metadata:
  name: chicmoz
build:
manifests:
  rawYaml:
    - ./common/namespace.yaml
    - ./explorer-ui/ingress.yaml
    - ./explorer-ui/deployment.yaml
    - ./explorer-ui/service.yaml
    - ./explorer-api/ingress.yaml
    - ./explorer-api/deployment.yaml
    - ./explorer-api/service.yaml
    - ./websocket-event-publisher/ingress.yaml
    - ./websocket-event-publisher/deployment.yaml
    - ./websocket-event-publisher/service.yaml
    - ./auth/deployment.yaml
    - ./auth/service.yaml
    - ./aztec-event-cannon/deployment.yaml
    - ./aztec-listener/deployment.yaml
    - ./ethereum-listener/deployment.yaml # NOTE: eth-listener is WIP!
    - ./kafka-ui/configmap.yaml
    - ./kafka-ui/configmap-env.yaml
    - ./kafka-ui/ingress.yaml
    - ./aztec-sandbox-node/ingress.yaml
    - ./aztec-sandbox-node/deployment.yaml
    - ./aztec-sandbox-node/service.yaml
    - ./anvil-ethereum-node/ingress.yaml
    - ./anvil-ethereum-node/deployment.yaml
    - ./anvil-ethereum-node/service.yaml
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: chicmoz
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
      - name: postgresql
        version: 12.10.0
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        valuesFiles:
          - ./postgres/values.yaml
        setValues:
          global.postgresql.auth.postgresPassword: "secret-local-password"
          global.postgresql.auth.username: "admin"
          global.postgresql.auth.password: "secret-local-password"
          image.debug: true
        namespace: chicmoz
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
      - name: redis
        version: 18.17.1
        remoteChart: redis
        repo: https://charts.bitnami.com/bitnami
        namespace: chicmoz
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
        setValues:
          auth.enabled: false
          master.configuration: |
            maxmemory 100mb
            maxmemory-policy volatile-ttl
            lazyfree-lazy-eviction yes
          replica.configuration: |
            maxmemory 100mb
            maxmemory-policy volatile-ttl
            lazyfree-lazy-eviction yes
          persistence.enabled: false
      - name: kafka
        version: 26.4.2
        remoteChart: kafka
        repo: https://charts.bitnami.com/bitnami
        namespace: chicmoz
        setValues:
          sasl.enabledMechanisms: plain
          sasl.controllerMechanism: plain
          sasl.interBrokerMechanism: plain
          sasl.controller.user: controller_user
          sasl.controller.password: test
          sasl.interbroker.user: inter_broker_user
          sasl.interbroker.password: test
          sasl.client.users:
            - controller_user
          sasl.client.passwords:
            - test
          extraConfig: |
            message.max.bytes=10000000
        createNamespace: false
        recreatePods: true
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
      - name: kafka-ui
        version: 0.7.6
        remoteChart: kafka-ui
        repo: https://provectus.github.io/kafka-ui-charts
        namespace: chicmoz
        setValues:
          yamlApplicationConfigConfigMap.name: kafka-ui-configmap
          yamlApplicationConfigConfigMap.keyName: config.yml
          existingConfigMap: kafka-ui-helm-values
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
