CREATE TABLE IF NOT EXISTS "l2_tips" (
	"l2_network_id" varchar PRIMARY KEY NOT NULL,
	"proposed_block_number" bigint NOT NULL,
	"proposed_block_hash" varchar NOT NULL,
	"proposed_checkpoint_block_number" bigint,
	"proposed_checkpoint_block_hash" varchar,
	"proposed_checkpoint_number" bigint,
	"proposed_checkpoint_hash" varchar,
	"checkpointed_block_number" bigint NOT NULL,
	"checkpointed_block_hash" varchar NOT NULL,
	"checkpointed_checkpoint_number" bigint NOT NULL,
	"checkpointed_checkpoint_hash" varchar NOT NULL,
	"proven_block_number" bigint NOT NULL,
	"proven_block_hash" varchar NOT NULL,
	"proven_checkpoint_number" bigint NOT NULL,
	"proven_checkpoint_hash" varchar NOT NULL,
	"finalized_block_number" bigint NOT NULL,
	"finalized_block_hash" varchar NOT NULL,
	"finalized_checkpoint_number" bigint NOT NULL,
	"finalized_checkpoint_hash" varchar NOT NULL,
	"observed_at" bigint NOT NULL,
	"aztec_node_name" varchar,
	"aztec_node_version" varchar,
	"degraded_reason" varchar,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
