import { AztecAddress, AztecScanNote, L2NetworkId } from "@chicmoz-pkg/types";

export const SERVICE_NAME = "explorer-api";

/* ⚠️ Aztec Scan Notes ⚠️
    Aztec Scan Notes are a way to add metadata to contracts on Aztec Scan. Preferably this should be done through the Aztec Scan UI, but for now we are adding them here manually.
    If you want to have your contract added here, please create a PR to this file.
*/
export const AZTEC_SCAN_NOTES: Record<
  L2NetworkId,
  Record<AztecAddress, AztecScanNote>
> = {
  MAINNET: {},
  SANDBOX: {
    "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa": {
      name: "Example",
      origin: "This is an example note",
      comment: "EXAMPLE",
      relatedL1ContractAddresses: [
        {
          address: "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          note: "This is an example note for the L1-contract",
        },
      ],
    },
  },
  DEVNET: {},
  TESTNET: {
    "0x0fb5144f2518c5501dfde73723cad1d1ac7f5a3ab15486ae4d444d228a205448": {
      name: "DAI test token",
      origin: "DeFi-wonderland",
      comment:
        "This is a test token deployed by DeFi-wonderland. It is a test token for the DAI token. It only has 9 decimals.",
    },
    "0x09db977a84f23f5294fd98a94f282bcaeefac30f5d3d546fd2413d8e7784b1ea": {
      name: "SHIPPED token",
      origin: "Aztec Team",
      comment:
        "This is one of the first contracts deployed testing the default token contract in Aztec-packages. The token is called 'SHIPPED'",
    },
    "0x1534cadfd4566b8ba7e4ad87f499db5e2df5f76d6014a04d19e14bf2018ee266": {
      name: "nemi.fi PoolManager",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This is the PoolManager singleton contract for nemi.fi. It manages all liquidity pools and routes swaps.",
    },
    "0x2e993924cdc5b9d1566f2669969fd07d7b8035eb2ab8ee6fe737df72d8b567ae": {
      name: "Obsidion Webauthn Authenticator",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This contract is an authenticator module contract that stores ECDSA secp256r1 signing keys for Obsidion accounts and exposes validation method for transaction signature generated by users through Webauthn.",
    },
    "0x12b7a98536c9ed58273bd1ba86fa63cc02751d9945b64b06eab87d53182773ad": {
      name: "Obsidion DevMode Authenticator",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This contract is another test-only authenticator module contract specifically built for users who don't have Touch ID on their laptop.",
    },
    "0x16fd882c721c8219c17f6b4158801858e60627df488e808830e5697ad09b29bd": {
      name: "Obsidion EmailRegistry",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This contract is a registry contract that manages mapping between user addresses and emails. This contract allows users to transfer tokens to other users by only knowing recipient's email address.",
    },
    "0x19f8873315cad78e160bdcb686bcdc8bd3760ca215966b677b79ba2cfb68c1b5": {
      name: "Obsidion Deployer FPC",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This contract is an account contract we use to deploy our contracts, which also has an ability to do fee sponsoring as FPC.",
    },
    "0x0df0b722ec3e476c556ff437981e10f75fae34f441dffd76e3c9c0a6d240f410": {
      name: "zkSnacks NFT collection",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This contract is the zkSnacks NFT collection. The first NFT collection on Aztec testnet. Get the taste of privacy. zksnacks.nemi.fi",
    },
    "0x2ab7cf582347c8a2834e0faf98339372118275997e14c5a77054bb345362e878": {
      name: "Clean USDC",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This is the Clean USDC Token contract deployed by bridge.human.tech",
      relatedL1ContractAddresses: [
        {
          address: "0x24ca8bf6d17d0f6844eacee733fa183d343c1dc4",
          note: "Test USDC on Sepolia",
        },
      ],
    },
    "0x2d964ce22db58c33f6e3e29cd2c2550ca310610f4917955ecb59bc7b6f97d6a7": {
      name: "Human Tech Bridge",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "This is the bridge contract deployed by bridge.human.tech. It allows users to bridge assets from Sepolia to Aztec testnet.",
      relatedL1ContractAddresses: [
        {
          address: "0x7e73a94be39327533faa90947cae5fc215349287",
          note: "Bridge portal contract on Sepolia",
        },
      ],
    },
    "0x266b64330cd6dedba8bae1a28c1abacb2a08148a229d7670f8d872340c937a08": {
      name: "Blocksense Network",
      origin: "Published in ecosystem Signal group pre public testnet launch",
      comment:
        "Decentralized oracle protocol that securely brings real-world data onto blockchains using zero-knowledge proofs and game-theoretic consensus mechanism.",
    },
  },
};

export const AZTEC_SCAN_MANUAL_SOURCE_CODE_URLS: Record<
  L2NetworkId,
  Record<AztecAddress, string>
> = {
  MAINNET: {},
  SANDBOX: {},
  TESTNET: {
    "0x27fdd1bf03d0717b0d1ba2b312b90bc9488997b2a00fec61514c77635cfc870c":
      "https://github.com/defi-wonderland/aztec-standards/tree/68855cd7012f4305489520e6de1fdc9c93f01050/src/token_contract",
  },
  DEVNET: {},
};
