apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../chicmoz-base-image.yaml
build:
  artifacts:
    - image: ethereum-listener
      context: ../../../services/ethereum-listener
      docker:
        dockerfile: Dockerfile
      requires:
        - image: chicmoz-base
          alias: BASE
