apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ethereum-listener
  name: ethereum-listener
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-listener
  strategy: {}
  template:
    metadata:
      labels:
        app: ethereum-listener
    spec:
      containers:
        - image: ethereum-listener:latest
          resources:
            limits:
              memory: 250Mi
              cpu: 100m
          name: ethereum-listener
          env:
            - name: NODE_ENV
              value: "development"
            - name: BLOCK_POLL_INTERVAL_MS
              value: "5000"
            - name: LISTENER_DISABLED
              value: "false"
            - name: GENESIS_CATCHUP
              value: "true"
            - name: LISTEN_FOR_BLOCKS
              value: "true"
            - name: ETHEREUM_HTTP_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: global
                  key: CHICMOZ_ETHEREUM_RPC_HTTP
            - name: ETHEREUM_WS_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: global
                  key: CHICMOZ_ETHEREUM_RPC_WS
status: {}
