[package]
name = "aztec_event_shooter" # can't use dashes in package name, so change cannon => shooter to emphasize that this is a different name
type = "contract"
authors = [ "" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.61.0", directory = "noir-projects/aztec-nr/aztec" }
