apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aztec-listener
  name: aztec-listener
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztec-listener
  strategy: {}
  template:
    metadata:
      labels:
        app: aztec-listener
    spec:
      initContainers:
        - name: run-migrations
          image: aztec-listener:latest
          command: ["yarn", run, "migrate"]
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-aztec-listener

          env:
            - name: TOTAL_DB_RESET
              value: "false"
      containers:
        - image: aztec-listener:latest
          resources:
            limits:
              memory: 750Mi
              cpu: 250m
          name: aztec-listener
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-aztec-listener
          env:
            - name: INSTANCE_NAME
              value: "local_aztec_sandbox_listener"
            - name: L2_NETWORK_ID
              value: "SANDBOX"
            - name: MAX_BATCH_SIZE_FETCH_MISSED_BLOCKS
              value: "50"
            - name: IGNORE_PROCESSED_HEIGHT
              value: "false"
            - name: AZTEC_DISABLED
              value: "false"
            - name: AZTEC_GENESIS_CATCHUP
              value: "true"
            - name: AZTEC_LISTEN_FOR_BLOCKS
              value: "true"
            - name: AZTEC_LISTEN_FOR_PENDING_TXS
              value: "true"
            - name: AZTEC_RPC_URL
              value: "http://aztec-sandbox-node:8081"
status: {}
