apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aztec-listener
  name: aztec-listener
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztec-listener
  strategy: {}
  template:
    metadata:
      labels:
        app: aztec-listener
    spec:
      initContainers:
        - name: run-migrations
          image: aztec-listener:latest
          command: ["yarn", run, "migrate"]
          env:
            - name: NODE_ENV
              value: "development"
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "aztec_listener"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
      containers:
        - image: aztec-listener:latest
          resources:
            limits:
              memory: 750Mi
              cpu: 250m
          name: aztec-listener
          env:
            - name: NODE_ENV
              value: "development"
            - name: BLOCK_INTERVAL_MS
              value: "2000"
            - name: BATCH_SIZE
              value: "50"
            - name: CHAIN_NAME
              value: "AZTEC"
            - name: NETWORK_NAME
              value: "SANDBOX"
            - name: MAX_BATCH_SIZE_FETCH_MISSED_BLOCKS
              value: "50"
            - name: DISABLE_AZTEC
              value: "false"
            - name: LISTEN_FOR_BLOCKS
              value: "true"
            - name: CATCHUP_ENABLED
              value: "false"
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "aztec_listener"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
            - name: AZTEC_RPC
              value: "http://host.minikube.internal:8080"
            - name: IGNORE_PROCESSED_HEIGHT
              value: "true"
status: {}
