apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aztec-listener
  name: aztec-listener
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztec-listener
  strategy: {}
  template:
    metadata:
      labels:
        app: aztec-listener
    spec:
      initContainers:
        - name: run-migrations
          image: aztec-listener:latest
          command: ["yarn", run, "migrate"]
          env:
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "aztec_listener"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
      containers:
        - image: aztec-listener:latest
          resources:
            limits:
              memory: 750Mi
              cpu: 250m
          name: aztec-listener
          env:
            - name: INSTANCE_NAME
              value: "remote_sp_testnet_aztec-listener"
            - name: BLOCK_POLL_INTERVAL_MS
              value: "5000"
            - name: L2_NETWORK_ID
              value: "SP_TESTNET"
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "aztec_listener"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
            - name: AZTEC_GENESIS_CATCHUP
              value: "true"
            - name: AZTEC_LISTEN_FOR_BLOCKS
              value: "true"
            - name: AZTEC_LISTEN_FOR_PENDING_TXS
              value: "true"
            - name: AZTEC_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: global
                  key: SP_TESTNET_AZTEC_L2_BOOTNODE_RPC
status: {}
