apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aztecscan-api-tls-testnet
  namespace: chicmoz-prod
spec:
  secretName: aztecscan-api-tls-testnet
  issuerRef:
    name: aztecscan-issuer-production
    kind: ClusterIssuer
  dnsNames:
    - api.testnet.aztecscan.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aztecscan-ui-tls-testnet
  namespace: chicmoz-prod
spec:
  secretName: aztecscan-ui-tls-testnet
  issuerRef:
    name: aztecscan-issuer-production
    kind: ClusterIssuer
  dnsNames:
    - testnet.aztecscan.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aztecscan-ws-tls-testnet
  namespace: chicmoz-prod
spec:
  secretName: aztecscan-ws-tls-testnet
  issuerRef:
    name: aztecscan-issuer-production
    kind: ClusterIssuer
  dnsNames:
    - ws.testnet.aztecscan.xyz
