apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: gateways-devnet
manifests:
  rawYaml:
    - ./gateway.yaml
    - ./beta/clienttrafficpolicy.yaml
    - ./devnet/certificates.yaml
    - ./devnet/certificates-beta.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
