apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../../common/chicmoz-base-image.yaml
build:
  artifacts:
    - image: registry.digitalocean.com/aztlan-containers/aztec-listener
      context: ../../../../services/aztec-listener
      docker:
        dockerfile: Dockerfile
      requires:
        - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
          alias: BASE
