apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: explorer-api-devnet
  namespace: chicmoz-prod
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: explorer-api-devnet
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  http:
    http1:
      maxRequestBodySize: 52428800
