apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorer-api-devnet-label
  name: explorer-api-devnet-deployment
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-api-devnet-label
  strategy: {}
  template:
    metadata:
      labels:
        app: explorer-api-devnet-label
    spec:
      imagePullSecrets:
        - name: registry-aztlan-containers
      initContainers:
        - image: registry.digitalocean.com/aztlan-containers/explorer-api:latest
          name: run-migrations
          command: ["yarn", run, "migrate"]
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-explorer-api-devnet
          env:
            - name: NODE_ENV
              value: "production"
            - name: TOTAL_DB_RESET
              value: "false"
      containers:
        - image: registry.digitalocean.com/aztlan-containers/explorer-api:latest
          name: explorer-api
          resources:
            limits:
              memory: 2048Mi
              cpu: 250m
          ports:
            - name: http-app-port
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-explorer-api-devnet
          env:
            - name: NODE_ENV
              value: "production"
            - name: INSTANCE_NAME
              value: "devnet_explorer-api"
            - name: L2_NETWORK_ID
              value: "DEVNET"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
