kind: Secret
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: chicmoz
type: Opaque
# TODO: use secret for password
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
        - name: sandbox-explorer-api-postgres
          type: grafana-postgresql-datasource
          uid: ae5es4xn8ny0we
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: explorer_api_sandbox
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
