apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: chicmoz-prod
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt1/postgres-data
