kind: Secret
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: chicmoz-staging
type: Opaque
# TODO: use secret for password
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
        - name: testnet-aztec-listener-postgres
          type: grafana-postgresql-datasource
          uid: cccccccccccccc
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: aztec_listener_testnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: testnet-ethereum-listener-postgres
          type: grafana-postgresql-datasource
          uid: gggggggggggggg
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: ethereum_listener_testnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: testnet-explorer-api-postgres
          type: grafana-postgresql-datasource
          uid: hhhhhhhhhhhhhh
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: explorer_api_testnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
