/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress } from "@aztec/aztec.js/addresses";
import {
  type AztecAddressLike,
  type ContractArtifact,
  type FieldLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { Fr } from "@aztec/aztec.js/fields";
import { PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import SimpleLoggingContractArtifactJson from "../../target/simple_logging-SimpleLogging.json" with { type: "json" };
export const SimpleLoggingContractArtifact = loadContractArtifact(
  SimpleLoggingContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract SimpleLogging;
 */
export class SimpleLoggingContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, SimpleLoggingContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): SimpleLoggingContract {
    return Contract.at(
      address,
      SimpleLoggingContract.artifact,
      wallet,
    ) as SimpleLoggingContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(
    wallet: Wallet,
    headstart: bigint | number,
    owner: AztecAddressLike,
  ) {
    return new DeployMethod<SimpleLoggingContract>(
      PublicKeys.default(),
      wallet,
      SimpleLoggingContractArtifact,
      (instance, wallet) => SimpleLoggingContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    headstart: bigint | number,
    owner: AztecAddressLike,
  ) {
    return new DeployMethod<SimpleLoggingContract>(
      publicKeys,
      wallet,
      SimpleLoggingContractArtifact,
      (instance, wallet) => SimpleLoggingContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<
    M extends keyof SimpleLoggingContract["methods"],
  >(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<SimpleLoggingContract["methods"][M]>
  ) {
    return new DeployMethod<SimpleLoggingContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      SimpleLoggingContractArtifact,
      (instance, wallet) => SimpleLoggingContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return SimpleLoggingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      SimpleLoggingContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<"counters"> {
    return {
      counters: {
        slot: new Fr(1n),
      },
    } as ContractStorageLayout<"counters">;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** decrement(owner: struct) */
    decrement: ((owner: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_counter(owner: struct) */
    get_counter: ((owner: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** increment(owner: struct) */
    increment: ((owner: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** increment_and_decrement(owner: struct) */
    increment_and_decrement: ((
      owner: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** increment_self_and_other(other_counter: struct, owner: struct) */
    increment_self_and_other: ((
      other_counter: AztecAddressLike,
      owner: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** increment_twice(owner: struct) */
    increment_twice: ((
      owner: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** initialize(headstart: integer, owner: struct) */
    initialize: ((
      headstart: bigint | number,
      owner: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
