apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../chicmoz-base-image.yaml
build:
  artifacts:
    - image: explorer-ui
      context: ../../../services/explorer-ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: "development"
          VITE_API_URL: "http://explorer-api.localhost:80/v1/d1e2083a-660c-4314-a6f2-1d42f4b944f4"
          VITE_WS_URL: "ws://ws.localhost:80" # TODO: use API_KEY
          VITE_DISCORD_URL: "https://discord.gg/obscura-network"
          VITE_X_URL: "https://x.com/Obscura_Network"
          VITE_GITHUB_URL: "https://github.com/aztlan-labs/chicmoz"
      requires:
        - image: chicmoz-base
          alias: BASE
