apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../common/skaffold.chicmoz-base-image.yaml
build:
  artifacts:
    - image: explorer-ui-remote-devnet
      context: ../../../services/explorer-ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: "development"
          VITE_L2_NETWORK_ID: "DEVNET"
          VITE_CHICMOZ_ALL_UI_URLS: "Sandbox|http://sandbox.chicmoz.localhost,Remote Devnet|http://remote-devnet.chicmoz.localhost"
          VITE_API_URL: "http://api.remote-devnet.chicmoz.localhost:80/v1"
          VITE_API_KEY: "dev-api-key"
          VITE_WS_URL: "ws://ws.remote-devnet.chicmoz.localhost:80"
          VITE_DISCORD_URL: "https://discord.gg/xnw7fVXB7m"
          VITE_GITHUB_URL: "https://github.com/aztec-scan/chicmoz"
          VITE_VERSION_STRING: "development-remote-devnet"
      requires:
        - image: chicmoz-base
          alias: BASE
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ./remote_devnet/service.yaml
    - ./remote_devnet/ingress.yaml
    - ./remote_devnet/deployment.yaml
