apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../common/skaffold.chicmoz-base-image.yaml
build:
  artifacts:
    - image: explorer-ui-sp-testnet
      context: ../../../services/explorer-ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: "development"
          VITE_L2_NETWORK_ID: "SP_TESTNET"
          VITE_CHICMOZ_ALL_UI_URLS: "Sandbox|http://sandbox.chicmoz.localhost,S&P-testnet|http://sp.chicmoz.localhost"
          VITE_API_URL: "http://api.sp.chicmoz.localhost:80/v1"
          VITE_API_KEY: "dev-api-key"
          VITE_WS_URL: "ws://ws.sp.chicmoz.localhost:80"
          VITE_DISCORD_URL: "https://discord.gg/obscura-build"
          VITE_X_URL: "https://x.com/Obscura_Build"
          VITE_GITHUB_URL: "https://github.com/aztlan-labs/chicmoz"
          VITE_VERSION_STRING: "developement-sp-testnet"
      requires:
        - image: chicmoz-base
          alias: BASE
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ./sp_testnet/service.yaml
    - ./sp_testnet/ingress.yaml
    - ./sp_testnet/deployment.yaml
