apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aztec-listener-sp-testnet-label
  name: aztec-listener-sp-testnet-deployment
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztec-listener-sp-testnet-label
  strategy: {}
  template:
    metadata:
      labels:
        app: aztec-listener-sp-testnet-label
    spec:
      initContainers:
        - name: run-migrations
          image: aztec-listener:latest
          command: ["yarn", run, "migrate"]
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-aztec-listener-sp-testnet
      containers:
        - image: aztec-listener:latest
          resources:
            limits:
              memory: 750Mi
              cpu: 500m
          name: aztec-listener
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-aztec-listener-sp-testnet
          env:
            - name: INSTANCE_NAME
              value: "sp_testnet_aztec-listener"
            - name: BLOCK_POLL_INTERVAL_MS
              value: "5000"
            - name: L2_NETWORK_ID
              value: "SP_TESTNET"
            - name: AZTEC_GENESIS_CATCHUP
              value: "true"
            - name: AZTEC_LISTEN_FOR_BLOCKS
              value: "true"
            - name: AZTEC_LISTEN_FOR_PENDING_TXS
              value: "true"
            - name: AZTEC_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: global
                  #key: SP_TESTNET_OBSCURA_L2_RPC_1
                  #key: SP_TESTNET_OBSCURA_L2_RPC_2
                  key: SP_TESTNET_AZTEC_L2_BOOTNODE_RPC
status: {}
