apiVersion: v1
data:
  POSTGRES_DB_NAME: aztec_listener_devnet
kind: ConfigMap
metadata:
  name: postgres-config-aztec-listener-devnet
  namespace: chicmoz-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aztec-listener
    app.kubernetes.io/name: aztec-listener
    app.kubernetes.io/part-of: chicmoz-prod
    network: devnet
  name: aztec-listener-devnet
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztec-listener
      network: devnet
  template:
    metadata:
      labels:
        app: aztec-listener
        network: devnet
    spec:
      containers:
        - env:
            - name: INSTANCE_NAME
              value: devnet_aztec-listener
            - name: L2_NETWORK_ID
              value: DEVNET
            - name: AZTEC_RPC_URLS
              valueFrom:
                secretKeyRef:
                  key: AZTEC_RPC_NODES_DEVNET
                  name: aztec-listener-devnet
            - name: NODE_ENV
              value: production
            - name: AZTEC_LISTEN_FOR_BLOCKS
              value: "true"
            - name: AZTEC_LISTEN_FOR_PENDING_TXS
              value: "true"
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-aztec-listener-devnet
          image: registry.digitalocean.com/aztlan-containers/aztec-listener-devnet:latest
          imagePullPolicy: Always
          name: aztec-listener
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
      imagePullSecrets:
        - name: registry-aztlan-containers
      initContainers:
        - command:
            - yarn
            - run
            - migrate
          env:
            - name: NODE_ENV
              value: production
            - name: TOTAL_DB_RESET
              value: "false"
          envFrom:
            - configMapRef:
                name: postgres-config-global
            - configMapRef:
                name: postgres-config-aztec-listener-devnet
          image: registry.digitalocean.com/aztlan-containers/aztec-listener-devnet:latest
          name: run-migrations
