apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ethereum-listener-devnet-label
  name: ethereum-listener-devnet-deployment
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-listener-devnet-label
  strategy: {}
  template:
    metadata:
      labels:
        app: ethereum-listener-devnet-label
    spec:
      imagePullSecrets:
        - name: registry-aztlan-containers
      containers:
        - image: registry.digitalocean.com/aztlan-containers/ethereum-listener:latest
          name: ethereum-listener
          resources:
            limits:
              memory: 150Mi
              cpu: 100m
          env:
            - name: NODE_ENV
              value: "production"
            - name: INSTANCE_NAME
              value: "ethereum-listener-devnet"
            - name: L2_NETWORK_ID
              value: "DEVNET"
            - name: LISTENER_DISABLED
              value: "false"
            - name: LISTEN_FOR_BLOCKS
              value: "true"
            - name: ETHEREUM_HTTP_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: global
                  key: DEVNET_AZTEC_L1_HTTP
            - name: ETHEREUM_WS_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: global
                  key: DEVNET_AZTEC_L1_WS
status: {}
