apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorer-ui-mainnet-label
  name: explorer-ui-mainnet-deployment
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-ui-mainnet-label
  template:
    metadata:
      labels:
        app: explorer-ui-mainnet-label
    spec:
      imagePullSecrets:
        - name: registry-aztlan-containers
      containers:
        - image: registry.digitalocean.com/aztlan-containers/explorer-ui-mainnet:latest
          name: explorer-ui-mainnet
          resources:
            limits:
              memory: 300Mi
              cpu: 200m
          ports:
            - name: http-app-port
              containerPort: 80
              protocol: TCP
          env:
            - name: VITE_CHICMOZ_ALL_UI_URLS
              value: "Mainnet|https://aztecscan.xyz,Testnet|https://testnet.aztecscan.xyz,Devnet|https://devnet.aztecscan.xyz"
            - name: VITE_API_URL
              value: "https://api.aztecscan.xyz/v1"
            - name: VITE_WS_URL
              value: "wss://ws.aztecscan.xyz"
