apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aztecscan-api-tls-devnet
  namespace: chicmoz-prod
spec:
  secretName: aztecscan-api-tls-devnet
  issuerRef:
    name: aztecscan-issuer-production
    kind: ClusterIssuer
  dnsNames:
    - api.devnet.aztecscan.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aztecscan-ui-tls-devnet
  namespace: chicmoz-prod
spec:
  secretName: aztecscan-ui-tls-devnet
  issuerRef:
    name: aztecscan-issuer-production
    kind: ClusterIssuer
  dnsNames:
    - devnet.aztecscan.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aztecscan-ws-tls-devnet
  namespace: chicmoz-prod
spec:
  secretName: aztecscan-ws-tls-devnet
  issuerRef:
    name: aztecscan-issuer-production
    kind: ClusterIssuer
  dnsNames:
    - ws.devnet.aztecscan.xyz
