[package]
name = "simple_logging_update"
type = "contract"
authors = [""]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.81.0", directory = "noir-projects/aztec-nr/aztec" }
