apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-swagger
  namespace: chicmoz-prod
  annotations:
    cert-manager.io/cluster-issuer: "aztecscan-issuer-production"
spec:
  ingressClassName: nginx
  tls:
    - secretName: aztecscan-swagger-tls
      hosts:
        - docs.aztecscan.xyz
  rules:
    - host: docs.aztecscan.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swagger-service
                port:
                  name: http
status:
  loadBalancer: {}
