apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorer-api
  name: explorer-api
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-api
  strategy: {}
  template:
    metadata:
      labels:
        app: explorer-api
    spec:
      initContainers:
        - name: run-migrations
          image: explorer-api:latest
          command: ["yarn", run, "migrate"]
          env:
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "explorer_api"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
            - name: TOTAL_DB_RESET
              value: "false"
      containers:
        - image: explorer-api:latest
          resources:
            limits:
              memory: 2048Mi
              cpu: 250m
          ports:
            - name: http-app
              containerPort: 80
              protocol: TCP
          name: explorer-api
          env:
            - name: PORT
              value: "80"
            - name: L2_NETWORK_ID
              value: "SP_TESTNET" # TODO: different yaml-files?
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "explorer_api"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
            - name: CACHE_TTL
              value: "2"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
