apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ./common/skaffold.base.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ./mainnet/postgres-config.yaml
    - ./mainnet/service.yaml
    - ./mainnet/httproute.yaml
    - ./mainnet/http-filter.yaml
    - ./mainnet/securitypolicy.yaml
    - ./mainnet/deployment.yaml
