apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-cannon-label
  name: event-cannon-deployment
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-cannon-label
  strategy: {}
  template:
    metadata:
      labels:
        app: event-cannon-label
    spec:
      containers:
        - image: event-cannon:latest
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
          name: event-cannon
          env:
            - name: AZTEC_RPC_URL
              value: "http://aztec-sandbox-node:8081"
            - name: ETHEREUM_RPC_URL
              value: "http://anvil-ethereum-node:8545"
            - name: EXPLORER_API_URL
              value: "http://explorer-api-sandbox-service:80"
            - name: INIFINITE_LOOP
              value: "false"
            - name: SCENARIO_SIMPLE_DEFAULT_ACCOUNT
              value: "true"
            - name: SCENARIO_TOKEN_CONTRACT
              value: "true"
            - name: SCENARIO_FUNCTIONS_VOTE
              value: "true"
            - name: SCENARIO_SIMPLE_CONTRACT
              value: "true"
            - name: SCENARIO_SIMPLE_LOG
              value: "true"
            - name: SCENARIO_L1L2_PUBLIC_MESSAGING
              value: "true"
            - name: SCENARIO_L1L2_PRIVATE_MESSAGING
              value: "true"
            #TODO: https://github.com/aztec-scan/chicmoz/issues/375
            - name: SCENARIO_DEPLOY_AND_UPDATE
              value: "false"
status: {}
