apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../common/skaffold.chicmoz-base-image.yaml
build:
  artifacts:
    - image: event-cannon
      context: ../../../services/event-cannon
      docker:
        dockerfile: Dockerfile
      requires:
        - image: chicmoz-base
          alias: BASE
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ./deployment.yaml
