apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ./skaffold.base.yaml
deploy:
  kubectl:
    flags:
      apply: ["--force"]
  helm: {}
manifests:
  rawYaml:
    - ./postgres-config.yaml
    - ../postgres/postgres.yaml
    - ../redis/redis.yaml
    - ../kafka/kafka.yaml
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: chicmoz
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
        setValues:
          controller.replicaCount: 1
          defaultBackend.enabled: false
