apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: chicmoz
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt1/postgres-data
