apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aztec-listener
  name: aztec-listener
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztec-listener
  strategy: {}
  template:
    metadata:
      labels:
        app: aztec-listener
    spec:
      imagePullSecrets:
        - name: do-registry
      containers:
        - image: registry.digitalocean.com/aztlan-containers/aztec-listener:latest
          resources:
            limits:
              memory: 750Mi
              cpu: 250m
          name: aztec-listener
          env:
            - name: NODE_ENV
              value: "development"
            - name: CHAIN_NAME
              value: "AZTEC"
            - name: NETWORK_NAME
              value: "SANDBOX"
            - name: MAX_BATCH_SIZE_FETCH_MISSED_BLOCKS
              value: "50"
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "azteclistener"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password"
            - name: AZTEC_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: global
                  key: CHICMOZ_AZTEC_RPC
            - name: AZTEC_GENESIS_CATCHUP
              value: "true"
            - name: IGNORE_PROCESSED_HEIGHT
              value: "true"
            - name: AZTEC_LISTEN_FOR_BLOCKS
              value: "true"
status: {}
