apiVersion: v1
kind: Service
metadata:
  name: aztec-listener
  namespace: chicmoz
spec:
  selector:
    app: aztec-listener
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: http-app
