apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../chicmoz-base-image.yaml
build:
  artifacts:
    - image: aztec-event-cannon
      context: ../../../services/aztec-event-cannon
      docker:
        dockerfile: Dockerfile
      requires:
        - image: chicmoz-base
          alias: BASE
