apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: aztec-event-cannon
  name: aztec-event-cannon
  namespace: chicmoz
spec:
  template:
    metadata:
      labels:
        app: aztec-event-cannon
    spec:
      restartPolicy: Never
      containers:
        - image: aztec-event-cannon:latest
          resources:
            limits:
              memory: 750Mi
              cpu: 250m
          name: aztec-event-cannon
          env:
            - name: NODE_ENV
              value: "development"
            - name: AZTEC_RPC_URL
              value: "http://aztec-sandbox-node:8081"
status: {}
