apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chicmoz-prod
nameSuffix: -devnet

resources:
  - ../../base
  - httproute.yaml

images:
  - name: registry.digitalocean.com/aztlan-containers/explorer-ui-v2
    newTag: devnet-latest
