apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: chicmoz
spec:
  selector:
    app: metrics
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: http-app
