apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: explorer-ui-devnet
  namespace: chicmoz-prod
spec:
  parentRefs:
    - name: aztecscan-gateway
      sectionName: ui-devnet-http
    - name: aztecscan-gateway
      sectionName: ui-devnet-https
    - name: aztecscan-gateway
      sectionName: ui-devnet-beta-http
    - name: aztecscan-gateway
      sectionName: ui-devnet-beta-https
  hostnames:
    - devnet.aztecscan.xyz
    - devnet.beta.aztecscan.xyz
  rules:
    - backendRefs:
        - name: explorer-ui-devnet-service
          port: 80
