apiVersion: v1
kind: Namespace
metadata:
  name: chicmoz-prod
  labels:
    name: chicmoz-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
