apiVersion: skaffold/v4beta6
kind: Config
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - ./namespace.yaml
    - ./postgres-config.yaml
    #- ./certificate.yaml
    - ../cert-manager/cert-staging-issuer.yaml
    - ../cert-manager/cert-production-issuer.yaml
    - ../cert-manager/ingress_nginx_svc_aztecscan.xyz.yaml
    - ../cert-manager/ingress_nginx_svc_aztecscout.xyz.yaml
