apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
      context: ../../../
      docker:
        dockerfile: Dockerfile
