apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - ./common/namespace.yaml
    - ./common/postgres-config.yaml
  helm:
    releases:
      - name: ingress-nginx # TODO: this is also in infra, is it necessary on light deployments?
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: ingress-nginx
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
        setValues:
          controller.allowSnippetAnnotations: false
          controller.config.enable-real-ip: "true"
          controller.config.proxy-add-original-uri-header: "true"
          controller.config.real-ip-header: "proxy_protocol"
          controller.config.use-forwarded-headers: "true"
          controller.config.use-proxy-protocol: "true"
          controller.config.set-real-ip-from: "0.0.0.0/0"
          controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-protocol: "tcp"
          controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-enable-proxy-protocol: "true"
