apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../../common/skaffold.chicmoz-base-image.yaml
build:
  artifacts:
    - image: registry.digitalocean.com/aztlan-containers/explorer-api
      context: ../../../../services/explorer-api
      docker:
        dockerfile: Dockerfile
      requires:
        - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
          alias: BASE
