apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: chicmoz-prod-testnet
requires:
  - path: k8s/production/common/skaffold.manifests.yaml
  - path: k8s/production/aztec-listener/skaffold.testnet.yaml
  - path: k8s/production/ethereum-listener/skaffold.testnet.yaml
  - path: k8s/production/explorer-api/skaffold.testnet.yaml
  - path: k8s/production/explorer-ui-v2/skaffold.testnet.yaml
  - path: k8s/production/websocket-event-publisher/skaffold.testnet.yaml
