apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: chicmoz-prod
build:
  artifacts:
    - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
      context: .
      docker:
        dockerfile: Dockerfile
    - image: registry.digitalocean.com/aztlan-containers/explorer-ui
      context: services/explorer-ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: "production"
          VITE_API_URL: "https://api.chicmoz.info/v1/d1e2083a-660c-4314-a6f2-1d42f4b944f4" # TODO: change the api key
      requires:
        - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
          alias: BASE
    - image: registry.digitalocean.com/aztlan-containers/auth
      context: services/auth
      docker:
        dockerfile: Dockerfile
      requires:
        - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
          alias: BASE
    - image: registry.digitalocean.com/aztlan-containers/aztec-listener
      context: services/aztec-listener
      docker:
        dockerfile: Dockerfile
      requires:
        - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
          alias: BASE
    - image: registry.digitalocean.com/aztlan-containers/explorer-api
      context: services/explorer-api
      docker:
        dockerfile: Dockerfile
      requires:
        - image: registry.digitalocean.com/aztlan-containers/chicmoz-base
          alias: BASE
manifests:
  rawYaml:
    - k8s/production/common/namespace.yaml
    - k8s/production/explorer-ui/ingress.yaml
    - k8s/production/explorer-ui/deployment.yaml
    - k8s/production/explorer-ui/service.yaml
    - k8s/production/explorer-api/ingress.yaml
    - k8s/production/explorer-api/deployment.yaml
    - k8s/production/explorer-api/service.yaml
    - k8s/production/auth/deployment.yaml
    - k8s/production/auth/service.yaml
    - k8s/production/aztec-listener/deployment.yaml
    - k8s/production/aztec-listener/service.yaml
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: ingress-nginx
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
        setValues:
          controller.allowSnippetAnnotations: false
          controller.config.enable-real-ip: "true"
          controller.config.proxy-add-original-uri-header: "true"
          controller.config.real-ip-header: "proxy_protocol"
          controller.config.use-forwarded-headers: "true"
          controller.config.use-proxy-protocol: "true"
          controller.config.set-real-ip-from: "0.0.0.0/0"
          controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-protocol: "tcp"
          controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-enable-proxy-protocol: "true"
