apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: full-prod
requires:
  - path: ./common/skaffold.manifests.yaml
  - path: ./common/skaffold.infra.yaml
  - path: ./skaffold.light.yaml
manifests:
  rawYaml:
    - k8s/production/cert-manager/cert-staging-issuer.yaml
    - k8s/production/cert-manager/cert-production-issuer.yaml
    - k8s/production/cert-manager/ingress_nginx_svc_aztecscan.xyz.yaml
    - k8s/production/cert-manager/ingress_nginx_svc_aztecscout.xyz.yaml
