apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: only-monitoring-prod
deploy:
  kubectl:
    flags:
      apply: ["--force"]
manifests:
  rawYaml:
    - k8s/production/monitoring/prometheus-rbac.yaml
    - k8s/production/monitoring/kube-state-metrics.yaml
    - k8s/production/monitoring/prometheus-config.yaml
    - k8s/production/monitoring/prometheus-pvc.yaml
    - k8s/production/monitoring/prometheus-deployment.yaml
    - k8s/production/monitoring/prometheus-service.yaml
    - k8s/production/monitoring/otel-collector-config.yaml
    - k8s/production/monitoring/otel-collector-deployment.yaml
    - k8s/production/monitoring/otel-collector-service.yaml
