kind: Secret
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: chicmoz-prod
type: Opaque
# TODO: use secret for password
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
        - name: sp-testnet-aztec-listener-postgres
          type: grafana-postgresql-datasource
          uid: cccccccccccccc
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: aztec_listener_sp_testnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: sp-testnet-ethereum-listener-postgres
          type: grafana-postgresql-datasource
          uid: gggggggggggggg
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: ethereum_listener_sp_testnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: sp-testnet-explorer-api-postgres
          type: grafana-postgresql-datasource
          uid: hhhhhhhhhhhhhh
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: explorer_api_sp_testnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: devnet-aztec-listener-postgres
          type: grafana-postgresql-datasource
          uid: iiiiiiiiiiiiii
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: aztec_listener_devnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: devnet-ethereum-listener-postgres
          type: grafana-postgresql-datasource
          uid: jjjjjjjjjjjjjj
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: ethereum_listener_devnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
        - name: devnet-explorer-api-postgres
          type: grafana-postgresql-datasource
          uid: kkkkkkkkkkkkkk
          url: postgresql:5432
          user: admin
          secureJsonData:
            password: "secret-local-password"
          jsonData:
            database: explorer_api_devnet
            sslmode: "disable"
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
