[package]
name = "explorer_showcase"
type = "contract"
authors = [""]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v5.0.0-rc.2", directory = "aztec" }
field_note = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v5.0.0-rc.2", directory = "field-note" }
