apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: registry-aztlan-containers
      containers:
        - image: registry.digitalocean.com/aztlan-containers/auth:latest
          resources:
            limits:
              memory: 500Mi
              cpu: 50m
          ports:
            - name: http-app
              containerPort: 80
              protocol: TCP
          name: auth
          env:
            - name: PORT
              value: "80"
            - name: POSTGRES_IP
              value: "postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: "auth"
            - name: POSTGRES_ADMIN
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "secret-local-password" # TODO: change to env-var
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
status: {}
