apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-label
  name: auth-deployment
  namespace: chicmoz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-label
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-label
    spec:
      imagePullSecrets:
        - name: registry-aztlan-containers
      containers:
        - image: registry.digitalocean.com/aztlan-containers/auth:latest
          resources:
            limits:
              memory: 500Mi
              cpu: 50m
          ports:
            - name: http-app-port
              containerPort: 80
              protocol: TCP
          name: auth
          envFrom:
            - configMapRef:
                name: postgres-config-global
          env:
            - name: PORT
              value: "80"
            - name: POSTGRES_DB_NAME
              value: "auth"
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
status: {}
