apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: chicmoz-prod
spec:
  selector:
    app: auth
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: http-app
