apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chicmoz-prod
nameSuffix: -devnet

resources:
  - ../../base

images:
  - name: registry.digitalocean.com/aztlan-containers/compiler-orchestrator
    newName: registry.digitalocean.com/aztlan-containers/compiler-orchestrator-devnet
    newTag: latest

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: compiler-orchestrator
      spec:
        template:
          spec:
            containers:
              - name: compiler-orchestrator
                env:
                  - name: INSTANCE_NAME
                    value: "devnet_compiler-orchestrator"
                  - name: L2_NETWORK_ID
                    value: "DEVNET"
                  - name: COMPILER_IMAGE
                    value: "registry.digitalocean.com/aztlan-containers/contract-compiler-devnet:5.0.0-rc.2"
