name: CI/CD Obscura Prod
# TODO

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  build_and_deploy:
    runs-on:
      labels: large-runner-gh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: "true"

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
        shell: bash

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login tt

      - name: Build and push Docker images
        run: |
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_DEFAULT_REGION
          skaffold run --filename k8s/production/skaffold.prod.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-3
        shell: bash
