name: CI/CD Obscura Prod
# TODO

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  build_and_deploy:
    runs-on:
      labels: large-runner-gh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: "true"

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
        shell: bash

      - name: Configure Digital Ocean CLI
        run: |
          echo $DOC_ACCESS_KEY_ID
          echo $DOC_SECRET_ACCESS_KEY
          echo $DOC_DEFAULT_REGION
          aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name obscura-prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 097733725684.dkr.ecr.eu-west-3.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker images
        run: |
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_DEFAULT_REGION
          skaffold run --filename k8s/production/skaffold.prod.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-3
        shell: bash
