apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: chicmoz-prod
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}

    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        metric_expiration: 5m

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
