apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ../chicmoz-base-image.yaml
build:
  artifacts:
    - image: websocket-event-publisher
      context: ../../../services/websocket-event-publisher
      docker:
        dockerfile: Dockerfile
      requires:
        - image: chicmoz-base
          alias: BASE
