apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: websocket-event-publisher-sp-testnet-label
  name: websocket-event-publisher-sp-testnet-deployment
  namespace: chicmoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-event-publisher-sp-testnet-label
  template:
    metadata:
      labels:
        app: websocket-event-publisher-sp-testnet-label
    spec:
      containers:
        - name: websocket-event-publisher
          image: websocket-event-publisher
          ports:
            - name: websocket-port
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: PORT
              value: "3000"
            - name: L2_NETWORK_ID
              value: "SP_TESTNET"
            - name: KAFKA_BROKERS
              value: "kafka-headless:9092"
            - name: KAFKA_CLIENT_ID
              value: "websocket-event-publisher"
            - name: KAFKA_GROUP_ID
              value: "websocket-event-publisher-group"
            - name: KAFKA_TOPIC
              value: "aztec-events"
            - name: ENVIRONMENT
              value: "sp_testnet"
